### API v1

GET http://localhost:8080/api/v1/tracker/instruction
Cookie:       session=10000000-2000-4000-8000-160000000000
X-Request-ID: 10000000-2000-4000-8000-160000000000

###

POST http://localhost:8080/api/v1/tracker/fingerprint
Content-Type: application/x-www-form-urlencoded
Cookie:       session=10000000-2000-4000-8000-160000000000
X-Request-ID: 10000000-2000-4000-8000-160000000000

fingerprint=a96f3e8efd95cb47f16185c1c887cbad

### Static

GET http://localhost:8080/assets/fingerprint2.min.js

### Profiling

GET http://localhost:8090/pprof/cmdline

###

GET http://localhost:8090/pprof/profile

###

GET http://localhost:8090/pprof/symbol

###

GET http://localhost:8090/pprof/trace

###

GET http://localhost:8090/debug/pprof/

### Monitoring

GET http://localhost:8091/monitoring

###

GET http://localhost:8091/vars

###
